:Author: aubreyli
:Email: {aubreylys@hotmail.com}
:Date: 25/04/2022
:Revision: version#
:License: Public Domain

= Project: Motion-Instrument

Arduino project using Nano IoT 33 and JS with Web Audio API to create synthesized music corresponding to body movement

== How to run the project

Arduino Connection:
1. Under WiFi_Connection, fill in the arduino secret with your own router's ssid and password
2. Under WiFi_Coonection, in WiFi_Connection.ino, change the ip address to your ip address
3. select the right board (Arduino IoT 33) and port, upload the program

Web Client Connection:
1. Make sure node is installed locally
2. Under root directory, use npm to install libraries
3. Under root directory, `npm run dev` to open frontend

Server Connection:
1. Make sure node is installed locally
2. Under src, `node main.js` to start the server


=== Folder structure

....
 root                => root directory
  ├── WiFi_Connection       => main Arduino files
  ├── index.html      => frontend
  ├── src          => scripts for server
....

=== License
N/A

=== Contributing
To contribute to this project please contact aubreyli at https://github.com/Aubrey-Li or https://id.arduino.cc/aubreyli


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
